sudo: required
language: go
go:
- 1.11.x
matrix:
  allow_failures:
  - go: tip
addons:
  ssh_known_hosts: github.com
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" && ! $(which nc) ]] ; then sudo apt-get install
  -y netcat ; fi
- sudo sysctl -w vm.max_map_count=262144
- docker-compose pull
- docker-compose up -d
- go get -u github.com/google/go-cmp/cmp
- go get -u github.com/fortytw2/leaktest
- go get -u github.com/olivere/elastic
- go get -u github.com/onsi/ginkgo/ginkgo
- go get -u github.com/onsi/gomega/...
- while ! nc -z localhost 9200; do sleep 1; done
- while ! nc -z localhost 9210; do sleep 1; done
install: true
script:
- go test -race -v .
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX=testing BRANCH_TO_MERGE_INTO=master GITHUB_REPO=AaHaInc/aggretastic
  /tmp/travis-automerge
env:
  global:
    secure: PASTE_YOUR_KEY_HERE
